db.ej4.insertMany([
    {
        _id:'1',
        matricula:2233225566,
        nombre:"paula",
        apellido:"lopez",
        sexo:"f",
        idg:1,
        edad:20,
       
    },
    {
        _id:'2',
        matricula:2233225345,
        nombre:"joel",
        apellido:"mendez",
        sexo:"m",
        idg:1,
        edad:25,
    },
    {
        _id:'3',
        matricula:2233285868,
        nombre:"fernando",
        apellido:"ramirez",
        sexo:"m",
        idg:2,
        edad:22,
    },
    {
        _id:'4',
        matricula:2233756765,
        nombre:"laura",
        apellido:"herrera",
        sexo:"f",
        idg:2,
        edad:25,
    },
    {
        _id:'5',
        matricula:2234568596,
        nombre:"mario",
        apellido:"torres",
        sexo:"m",
        idg:3,
        edad:30,
    },
    {
        _id:'6',
        matricula:2296856777,
        nombre:"carla",
        apellido:"lopez",
        sexo:"f",
        idg:3,
        edad:23,
    },
  ])
    
   